[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18.18.0"
  
# Environment değişkenleri - backend URL'ini ekleyelim
[context.production.environment]
  VITE_API_URL = "https://job-portal-backend-7dvf.onrender.com"