[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18.18.0"
  
# Environment değişkenleri - backend URL'ini güncelledik
[context.production.environment]
  VITE_API_URL = "https://job-portal-gfus.onrender.com"
  
# CORS için _headers dosyası ekle
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Accept, Origin, X-Requested-With"