version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-5555}:${PORT:-5555}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-5555}
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
      - TS_NODE_TRANSPILE_ONLY=true
      - TS_NODE_SKIP_PROJECT=true 