version: '3.8'

services:
  mongo:
    image: mongo
    container_name: job-portal-mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  server:
    build: ./server
    container_name: job-portal-server
    ports:
      - "${PORT:-5555}:${PORT:-5555}"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-5555}
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
      - TS_NODE_TRANSPILE_ONLY=true
      - TS_NODE_SKIP_PROJECT=true
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    container_name: job-portal-client
    ports:
      - "5137:5137"
    tty: true
    stdin_open: true
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongo-data: