[phases.setup]
nixPkgs = ["nodejs_18", "yarn"]

[phases.install]
cmds = [
  "cd client && npm install",
  "cd server && npm install"
]

[phases.build]
cmds = [
  "cd client && npm run build"
]

[start]
cmd = "cd server && TS_NODE_TRANSPILE_ONLY=true TS_NODE_SKIP_PROJECT=true npx ts-node src/server.ts" 